services:
  nestquest.api:
    image: ${DOCKER_REGISTRY-}nestquestapi
    container_name: NestQuest.Api
    build:
      context: .
      dockerfile: src/NestQuest.Api/Dockerfile
    restart: always
    depends_on:
      - nestquest-db

  nestquest-db:
    image: postgres:latest
    container_name: NestQuest.Db
    environment:
      - POSTGRES_DB=nestquest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nestquest-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: NestQuest.Identity
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/nestquest-realm-export.json:/opt/keycloak/data/import/realm.json
    ports:
      - 18080:8080

  nestquest-seq:
    image: datalust/seq:latest
    container_name: NestQuest.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  nestquest-redis:
    image: redis:latest
    container_name: NestQuest.Redis
    restart: always
    ports:
      - '6379:6379'
